/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_Differentiator */

#ifndef _Included_util_Differentiator
#define _Included_util_Differentiator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_Differentiator
 * Method:    differentiate
 * Signature: (Lutil/Function;DD)D
 */
JNIEXPORT jdouble JNICALL Java_util_Differentiator_differentiate
  (JNIEnv *, jobject, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
