/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util_Integrator */

#ifndef _Included_util_Integrator
#define _Included_util_Integrator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util_Integrator
 * Method:    integrate
 * Signature: (Lutil/Function;DDD)D
 */
JNIEXPORT jdouble JNICALL Java_util_Integrator_integrate
  (JNIEnv *, jobject, jobject, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
